name: Master Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ayden
        password: ${{ secrets.VM_Pass }}
        script: |
          cd qr-image-drop
          echo ${{ secrets.VM_Pass }} | sudo -S pkill gunicorn
          git pull
          echo ${{ secrets.VM_Pass }} | sudo -S ./prod.sh
